
(defparameter *a* (make regular-relative-path :pathlist '("foo" "bar")))
(ensure (string= "foo/bar" (native-path *a*)))
(ensure (string-equal "(PATH \"foo/bar\")" (format nil "~S" *a*)))
(ensure (path= (make current-dir) (pathroot *a*)))
(ensure (equal '("foo" "bar") (pathlist *a*)))
(ensure (not (absolutep *a*)))
(defparameter *b* (make regular-absolute-path :pathlist '("foo" "bar")))
(ensure (string-equal "(PATH \"/foo/bar\")" (format nil "~S" *b*)))
(ensure (absolutep *b*))
(ensure (path= (make root-dir) (pathroot *b*)))
(ensure (not (path= *a* *b*)))
(ensure (path= (make regular-absolute-path :pathlist '("foo" "bar" "foo" "bar"))
	       (join-paths *b* *a*)))
